version: '3.4'
services:
  hovr:
    build: .
    image: hovr:0.1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      DJANGO_CONFIG_DATABASES_default_ENGINE: django.db.backends.sqlite3
      DJANGO_CONFIG_DATABASES_default_NAME: /var/hovr/data/db.sqlite3
      DJANGO_CONFIG_DATABASES_default_USER:
      DJANGO_CONFIG_DATABASES_default_PASSWORD:
      DJANGO_CONFIG_DATABASES_default_HOST:
      DJANGO_CONFIG_DATABASES_default_PORT:
    ports:
      - "${HOVR_PORT}:8000"
    volumes:
      - /data2/public/nvr:/hovr_data
      - hovr_db:/var/hovr/data
    tmpfs: /tmp


volumes:
  hovr_db: